# Generated by Django 3.2.5 on 2021-08-04 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('rfc', models.CharField(max_length=30, null=True)),
                ('nombre_completo', models.CharField(max_length=40, null=True)),
                ('cargo', models.CharField(max_length=30)),
                ('telefono', models.IntegerField(max_length=15)),
                ('razon_social', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Cotizaciones',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('fecha_ini', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('comentario', models.CharField(max_length=254)),
                ('subtotal', models.FloatField()),
                ('viaticos', models.FloatField()),
                ('descuento', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('total_sin_iva', models.FloatField()),
                ('is_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.PositiveIntegerField()),
                ('detalle', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Serv_Cot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.cotizaciones')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('num_interior', models.IntegerField(null=True)),
                ('num_exterior', models.IntegerField(null=True)),
                ('calle', models.CharField(max_length=50, null=True)),
                ('colonia', models.CharField(max_length=20, null=True)),
                ('pais', models.CharField(max_length=15)),
                ('referencia', models.CharField(max_length=254, null=True)),
                ('localidad', models.CharField(max_length=30, null=True)),
                ('estado', models.CharField(max_length=20, null=True)),
                ('municipio', models.CharField(max_length=20, null=True)),
                ('codigo_postal', models.PositiveIntegerField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.cliente')),
            ],
        ),
    ]
