# Generated by Django 3.2.6 on 2021-08-11 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20210810_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='general.empresa'),
        ),
    ]
