# Generated by Django 3.2.6 on 2021-08-23 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_alter_cliente_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='rfc',
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_ad',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='n_cliente',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='rfc',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='id_direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='general.direccion'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='id_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='general.empresa'),
        ),
    ]
