# Generated by Django 3.2.7 on 2021-09-13 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20210823_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('nombre', models.TextField(verbose_name='cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargo',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['id'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='general.empresa', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_completo',
            field=models.CharField(max_length=40, null=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=12, verbose_name='telefono'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_ad',
            field=models.CharField(max_length=12, null=True, verbose_name='telefono_ad'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='detalle',
            field=models.CharField(max_length=254, verbose_name='detalle'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.PositiveIntegerField(verbose_name='precio'),
        ),
        migrations.AlterModelTable(
            name='servicio',
            table='servicio',
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='general.cargo', verbose_name='cargo')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['id'],
            },
        ),
    ]
