# Generated by Django 3.2.7 on 2021-09-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_alter_cargo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
    ]
