# Generated by Django 3.2.7 on 2021-09-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_auto_20210914_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='detalle',
            field=models.TextField(verbose_name='detalle'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='nombre'),
        ),
    ]
