# Generated by Django 3.2.7 on 2021-09-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_alter_servicio_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('precio', models.PositiveIntegerField(verbose_name='precio')),
                ('detalle', models.TextField(verbose_name='detalle')),
                ('marca', models.CharField(max_length=50, verbose_name='marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='model')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Producto',
                'db_table': 'producto',
                'ordering': ['id'],
            },
        ),
    ]
