# Generated by Django 3.2.7 on 2021-09-27 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0014_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['id'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id_empresa',
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='general.sucursal', verbose_name='sucursal'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='calle',
            field=models.CharField(max_length=50, null=True, verbose_name='calle'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='codigo_postal',
            field=models.PositiveIntegerField(verbose_name='codigo_postal'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='colonia',
            field=models.CharField(max_length=20, null=True, verbose_name='colonia'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='estado',
            field=models.CharField(max_length=20, null=True, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='localidad',
            field=models.CharField(max_length=30, null=True, verbose_name='localidad'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='municipio',
            field=models.CharField(max_length=20, null=True, verbose_name='municipio'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='num_exterior',
            field=models.IntegerField(null=True, verbose_name='num_exterior'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='num_interior',
            field=models.IntegerField(null=True, verbose_name='num_interior'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='pais',
            field=models.CharField(max_length=15, verbose_name='pais'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='referencia',
            field=models.CharField(max_length=254, null=True, verbose_name='referencia'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(max_length=50, verbose_name='razon_social'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='id_direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='general.direccion', verbose_name='direccion'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='id_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='general.empresa', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='n_cliente',
            field=models.CharField(max_length=10, null=True, verbose_name='n_cliente'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='rfc',
            field=models.CharField(max_length=30, null=True, verbose_name='rfc'),
        ),
        migrations.AlterModelTable(
            name='cargo',
            table='g_cargo',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='g_producto',
        ),
        migrations.AlterModelTable(
            name='servicio',
            table='g_servicio',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='g_usuarios',
        ),
    ]
