# Generated by Django 3.2.7 on 2021-09-27 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0017_auto_20210926_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id_sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='general.sucursal', verbose_name='id_sucursal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_completo',
            field=models.CharField(max_length=40, null=True, verbose_name='nombre_completo'),
        ),
    ]
