# Generated by Django 3.2.7 on 2021-09-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0018_auto_20210926_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
