# Generated by Django 3.2.7 on 2021-10-04 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0019_auto_20210926_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='n_cliente',
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('n_entrada', models.AutoField(primary_key=True, serialize=False, verbose_name='n_entrada')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('marca', models.CharField(max_length=50, verbose_name='marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='model')),
                ('serie', models.CharField(max_length=15, verbose_name='detalle')),
                ('identificacion', models.CharField(max_length=10, verbose_name='identificacion')),
                ('descripcion_particular', models.CharField(max_length=25, verbose_name='descripcion_particular')),
                ('fecha_de_recepcion', models.DateField(verbose_name='fecha_de_recepcion')),
                ('modo', models.CharField(choices=[('PA', 'Paqueteria'), ('AB', 'AbaaRecogio'), ('CE', 'ClienteEntrego')], max_length=15)),
                ('estatus', models.CharField(choices=[('DE', 'Devuelto'), ('PE', 'Pendiente'), ('AP', 'Aprobado')], max_length=15)),
                ('orden_compra', models.CharField(max_length=15, verbose_name='orden_ compra')),
                ('n_cotizacion', models.CharField(max_length=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='general.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'Recepciones',
                'verbose_name_plural': 'Recepciones',
                'db_table': 'g_recepcion',
                'ordering': ['n_entrada'],
            },
        ),
    ]
