# Generated by Django 3.2.7 on 2021-10-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0020_auto_20211004_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcion',
            name='estatus',
            field=models.CharField(choices=[('Devuelto', 'Devuelto'), ('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='modo',
            field=models.CharField(choices=[('Paqueteria', 'Paqueteria'), ('Abaa Recogio', 'AbaaRecogio'), ('Cliente Entrego', 'ClienteEntrego')], max_length=15),
        ),
    ]
