# Generated by Django 3.2.7 on 2021-10-22 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0022_alter_recepcion_fecha_de_recepcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcion',
            name='fecha_de_recepcion',
            field=models.DateField(null=True, verbose_name='fecha_de_recepcion'),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='n_cotizacion',
            field=models.CharField(max_length=15, verbose_name='cotizacion'),
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serv_prest', models.CharField(choices=[('Calibracion', 'Calibracion'), ('Calificacion', 'Calificacion')], max_length=15, verbose_name='serv_prest')),
                ('fecha_ingreso', models.DateField(verbose_name='fecha_almacen')),
                ('n_recepcion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='general.recepcion', verbose_name='n_entrada')),
                ('n_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='general.servicio', verbose_name='servicio')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'db_table': 'g_ingresos',
                'ordering': ['id'],
            },
        ),
    ]
